apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: keycloak-tmp
  namespace: fleet-local
spec:
  helm:
    pollingInterval: 1m
    repo: oci://harbor.ryzen.me/library/keycloak
    version: 0.1.0
    values:
      config: 
        hostname: https://auth.ryzen.me

      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: cert-issuer
        tls:
          secretName: outline-tls

      database:
        existing: false
        secret:
          existing: true
          name: keycloak-postgresql-app
          usernameKey: username
          passwordKey: password
          databaseKey: dbname
          hostKey: host
        # persistence:
        #   storageClass: retain
  defaultNamespace: keycloak-tmp