apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgresql
  namespace: keycloak
spec:
  instances: 3
  storage:
    size: 5Gi
    storageClass: retain
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak